<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Knowledge;

class KnowledgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Knowledge::create([
            'id_penyakit'=>1,
            'id_gejala'=>1,
            'MB'=>'0,7',
            'MD'=>'0,2',
        ]);
        Knowledge::create([
            'id_penyakit'=>1,
            'id_gejala'=>2,
            'MB'=>'0,7',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>2,
            'id_gejala'=>3,
            'MB'=>'0,7',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>2,
            'id_gejala'=>4,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>3,
            'id_gejala'=>5,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>3,
            'id_gejala'=>6,
            'MB'=>'0,7',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>4,
            'id_gejala'=>7,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>4,
            'id_gejala'=>8,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>4,
            'id_gejala'=>9,
            'MB'=>'0,7',
            'MD'=>'0,2',
        ]);
        Knowledge::create([
            'id_penyakit'=>4,
            'id_gejala'=>10,
            'MB'=>'0,7',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>5,
            'id_gejala'=>11,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>5,
            'id_gejala'=>12,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>6,
            'id_gejala'=>13,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>6,
            'id_gejala'=>14,
            'MB'=>'0,7',
            'MD'=>'0,2',
        ]);
        Knowledge::create([
            'id_penyakit'=>6,
            'id_gejala'=>15,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>7,
            'id_gejala'=>16,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>7,
            'id_gejala'=>17,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>8,
            'id_gejala'=>7,
            'MB'=>'0,7',
            'MD'=>'0,2',
        ]);
        Knowledge::create([
            'id_penyakit'=>8,
            'id_gejala'=>18,
            'MB'=>'0,7',
            'MD'=>'0,2',
        ]);
        Knowledge::create([
            'id_penyakit'=>9,
            'id_gejala'=>7,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>9,
            'id_gejala'=>19,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>9,
            'id_gejala'=>20,
            'MB'=>'0,8',
            'MD'=>'0,2',
        ]);
        Knowledge::create([
            'id_penyakit'=>10,
            'id_gejala'=>21,
            'MB'=>'0,7',
            'MD'=>'0,2',
        ]);
        Knowledge::create([
            'id_penyakit'=>11,
            'id_gejala'=>22,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
        Knowledge::create([
            'id_penyakit'=>11,
            'id_gejala'=>23,
            'MB'=>'0,8',
            'MD'=>'0,1',
        ]);
    }
}
